version: "3.3"
services:
  db:
    container_name: vaccinations-postgres
    restart: always
    image: vaccinations-database   
    build:
      context: ./db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - network
    ports:
      - 5432:5432

  graphql:
    container_name: vaccine-graphql
    restart: always
    image: vaccine-graphql
    build:
      context: ./graphql
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - network
    ports:
      #- 5433:5433
      - 5000:5000
    #command: "--cors --connection ${DATABASE_URL} --port 5433 --schema ${SCHEMA} --append-plugins /usr/postgraphile/node_modules/@graphile-contrib/pg-simplify-inflector,/usr/postgraphile/filters/arrivedEarlierThan.js,/usr/postgraphile/filters/arrivedLaterThan.js,/usr/postgraphile/filters/expiresEarlierThan.js,/usr/postgraphile/filters/expiresLaterThan.js"
    command: "--cors --connection ${DATABASE_URL} --port 5000 --schema ${SCHEMA} --append-plugins /usr/postgraphile/node_modules/@graphile-contrib/pg-simplify-inflector,/usr/postgraphile/filters/arrivedEarlierThan.js,/usr/postgraphile/filters/arrivedLaterThan.js,/usr/postgraphile/filters/expiresEarlierThan.js,/usr/postgraphile/filters/expiresLaterThan.js"

  nginx:
    container_name: vaccine-nginx
    restart: always
    image: vaccine-nginx
    build:
      context: ./nginx
    env_file:
      - ./.env
    depends_on:
      - db
      - graphql
    networks:
      - network
    ports:
      - 8080:80

networks:
  network:

volumes:
  db: